[28 Oct 2021 | 01:51:30] WARNING in loader.py function <module> line 22 :: Не забудьте запустить redis-server!
[28 Oct 2021 | 01:51:30] SUCCESS in loader.py function <module> line 38 :: Подключение к Redis
[28 Oct 2021 | 01:51:30] SUCCESS in loader.py function <module> line 53 :: Подключение к PostgreSQL
[28 Oct 2021 | 01:51:31] SUCCESS in bot.py function main line 32 :: Бот запущен
[28 Oct 2021 | 01:51:44] INFO in base.py function start line 23 :: Пользователь 786711981 поменял состояние на <State 'ChoosingClass:choosing_class_num'>
[28 Oct 2021 | 01:51:48] INFO in users.py function delete line 45 :: Удален пользователь from_id=786711981, class_=11в, group=2
[28 Oct 2021 | 01:51:53] INFO in base.py function start line 23 :: Пользователь 786711981 поменял состояние на <State 'ChoosingClass:choosing_class_num'>
[28 Oct 2021 | 01:51:54] INFO in choosing_class.py function choose_class_num line 23 :: Пользователь 786711981 поменял состояние на ChoosingClass:choosing_class_letter
[28 Oct 2021 | 01:51:55] INFO in choosing_class.py function choose_letter line 43 :: Пользователь 786711981 поменял состояние на ChoosingClass:choosing_class_group
[28 Oct 2021 | 01:51:56] INFO in users.py function insert line 33 :: Добавлен пользователь from_id=786711981, class_='5в', group=1
[28 Oct 2021 | 01:52:01] INFO in users.py function delete line 45 :: Удален пользователь from_id=786711981, class_=5в, group=1
[28 Oct 2021 | 01:52:04] INFO in base.py function start line 23 :: Пользователь 786711981 поменял состояние на <State 'ChoosingClass:choosing_class_num'>
[28 Oct 2021 | 01:52:05] INFO in choosing_class.py function choose_class_num line 23 :: Пользователь 786711981 поменял состояние на ChoosingClass:choosing_class_letter
[28 Oct 2021 | 01:52:07] INFO in choosing_class.py function choose_letter line 43 :: Пользователь 786711981 поменял состояние на ChoosingClass:choosing_class_group
[28 Oct 2021 | 01:52:08] INFO in users.py function insert line 33 :: Добавлен пользователь from_id=786711981, class_='11в', group=1
[28 Oct 2021 | 01:52:43] INFO in users.py function delete line 45 :: Удален пользователь from_id=786711981, class_=11в, group=1
[28 Oct 2021 | 01:52:46] INFO in base.py function start line 23 :: Пользователь 786711981 поменял состояние на <State 'ChoosingClass:choosing_class_num'>
[28 Oct 2021 | 01:52:47] INFO in choosing_class.py function choose_class_num line 23 :: Пользователь 786711981 поменял состояние на ChoosingClass:choosing_class_letter
[28 Oct 2021 | 01:52:48] INFO in choosing_class.py function choose_letter line 43 :: Пользователь 786711981 поменял состояние на ChoosingClass:choosing_class_group
[28 Oct 2021 | 01:52:49] INFO in users.py function insert line 33 :: Добавлен пользователь from_id=786711981, class_='11в', group=2
[28 Oct 2021 | 01:54:45] DEBUG in bot.py function main line 37 :: Бот выключен
[28 Oct 2021 | 02:03:08] WARNING in loader.py function <module> line 22 :: Не забудьте запустить redis-server!
[28 Oct 2021 | 02:03:08] SUCCESS in loader.py function <module> line 38 :: Подключение к Redis
[28 Oct 2021 | 02:03:08] SUCCESS in loader.py function <module> line 53 :: Подключение к PostgreSQL
[28 Oct 2021 | 02:03:09] SUCCESS in bot.py function main line 32 :: Бот запущен
[28 Oct 2021 | 02:03:23] DEBUG in bot.py function main line 37 :: Бот выключен
[28 Oct 2021 | 02:07:51] WARNING in loader.py function <module> line 22 :: Не забудьте запустить redis-server!
[28 Oct 2021 | 02:07:51] SUCCESS in loader.py function <module> line 38 :: Подключение к Redis
[28 Oct 2021 | 02:07:51] SUCCESS in loader.py function <module> line 53 :: Подключение к PostgreSQL
[28 Oct 2021 | 02:07:51] SUCCESS in bot.py function main line 32 :: Бот запущен
[28 Oct 2021 | 02:08:02] DEBUG in bot.py function main line 37 :: Бот выключен
[28 Oct 2021 | 02:09:22] WARNING in loader.py function <module> line 22 :: Не забудьте запустить redis-server!
[28 Oct 2021 | 02:09:22] SUCCESS in loader.py function <module> line 38 :: Подключение к Redis
[28 Oct 2021 | 02:09:22] SUCCESS in loader.py function <module> line 53 :: Подключение к PostgreSQL
[28 Oct 2021 | 02:09:23] SUCCESS in bot.py function main line 32 :: Бот запущен
[28 Oct 2021 | 02:12:54] DEBUG in bot.py function main line 37 :: Бот выключен
[28 Oct 2021 | 02:13:01] WARNING in loader.py function <module> line 23 :: Не забудьте запустить redis-server!
[28 Oct 2021 | 02:13:01] SUCCESS in loader.py function <module> line 41 :: Подключение к Redis
[28 Oct 2021 | 02:13:01] SUCCESS in loader.py function <module> line 56 :: Подключение к PostgreSQL
[28 Oct 2021 | 02:13:01] SUCCESS in bot.py function main line 32 :: Бот запущен
[28 Oct 2021 | 02:13:37] DEBUG in bot.py function main line 38 :: Бот выключен
[28 Oct 2021 | 02:17:31] WARNING in loader.py function <module> line 23 :: Не забудьте запустить redis-server!
[28 Oct 2021 | 02:17:31] SUCCESS in loader.py function <module> line 41 :: Подключение к Redis
[28 Oct 2021 | 02:17:31] SUCCESS in loader.py function <module> line 56 :: Подключение к PostgreSQL
[28 Oct 2021 | 02:17:32] SUCCESS in bot.py function main line 32 :: Бот запущен
[28 Oct 2021 | 02:23:58] DEBUG in bot.py function main line 38 :: Бот выключен
[28 Oct 2021 | 02:30:00] WARNING in loader.py function <module> line 23 :: Не забудьте запустить redis-server!
[28 Oct 2021 | 02:30:01] WARNING in loader.py function <module> line 23 :: Не забудьте запустить redis-server!
[28 Oct 2021 | 02:33:59] SUCCESS in loader.py function <module> line 32 :: redis-server launched
[28 Oct 2021 | 02:33:59] SUCCESS in loader.py function <module> line 42 :: Подключение к Redis
[28 Oct 2021 | 02:33:59] SUCCESS in loader.py function <module> line 57 :: Подключение к PostgreSQL
[28 Oct 2021 | 02:33:59] SUCCESS in bot.py function main line 32 :: Бот запущен
[28 Oct 2021 | 02:34:10] INFO in base.py function start line 23 :: Пользователь 786711981 поменял состояние на <State 'ChoosingClass:choosing_class_num'>
[28 Oct 2021 | 02:34:16] INFO in users.py function delete line 45 :: Удален пользователь from_id=786711981, class_=11в, group=2
[28 Oct 2021 | 02:34:27] INFO in base.py function start line 23 :: Пользователь 786711981 поменял состояние на <State 'ChoosingClass:choosing_class_num'>
[28 Oct 2021 | 02:34:28] INFO in choosing_class.py function choose_class_num line 23 :: Пользователь 786711981 поменял состояние на ChoosingClass:choosing_class_letter
[28 Oct 2021 | 02:34:29] INFO in choosing_class.py function choose_letter line 43 :: Пользователь 786711981 поменял состояние на ChoosingClass:choosing_class_group
[28 Oct 2021 | 02:34:31] INFO in users.py function insert line 33 :: Добавлен пользователь from_id=786711981, class_='11в', group=2
[28 Oct 2021 | 02:34:42] DEBUG in bot.py function main line 38 :: Бот выключен
[28 Oct 2021 | 14:05:27] SUCCESS in loader.py function <module> line 33 :: redis-server launched
[28 Oct 2021 | 14:05:27] SUCCESS in loader.py function <module> line 43 :: Подключение к Redis
[28 Oct 2021 | 14:05:29] SUCCESS in loader.py function <module> line 63 :: Подключение к PostgreSQL
[28 Oct 2021 | 14:05:33] ERROR in executor.py function _wrap_callback line 260 :: An error has been caught in function '_wrap_callback', process 'MainProcess' (10672), thread 'MainThread' (8400):
Traceback (most recent call last):

  File "D:\Документы\Projects\school-timetable-bot\bot.py", line 48, in <module>
    start_webhook(dp, WEBHOOK_PATH, on_startup=on_startup, on_shutdown=on_shutdown,
    │             │   │                        │                       └ <function on_shutdown at 0x0000025F95173310>
    │             │   │                        └ <function on_startup at 0x0000025F9516DF70>
    │             │   └ '/2041745221:AAE_8yJ8SpeNMWNPFBf8a5ff8gXXt9J5UmQ'
    │             └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000025F94F7B100>
    └ <function start_webhook at 0x0000025F93C2F430>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 108, in start_webhook
    executor.run_app(**kwargs)
    │        │         └ {'host': '0.0.0.0', 'port': 3001}
    │        └ <function Executor.run_app at 0x0000025F93C2FC10>
    └ <aiogram.utils.executor.Executor object at 0x0000025F91051FD0>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 292, in run_app
    web.run_app(self._web_app, **kwargs)
    │   │       │    │           └ {'host': '0.0.0.0', 'port': 3001}
    │   │       │    └ <Application 0x25f90f831f0>
    │   │       └ <aiogram.utils.executor.Executor object at 0x0000025F91051FD0>
    │   └ <function run_app at 0x0000025F939D2E50>
    └ <module 'aiohttp.web' from 'C:\\Users\\creeper\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiohttp\\web....

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\web.py", line 508, in run_app
    loop.run_until_complete(main_task)
    │    │                  └ <Task pending name='Task-6' coro=<_run_app() running at C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-pack...
    │    └ <function BaseEventLoop.run_until_complete at 0x0000025F92BA0A60>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000025F92C70280>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000025F92BA3550>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000025F92B30EE0>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000025F9519B910>(<Future finished result=None>)>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x0000025F9519B910>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x0000025F9519B910>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x0000025F9519B910>(<Future finished result=None>)>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\web.py", line 319, in _run_app
    await runner.setup()
          │      └ <function BaseRunner.setup at 0x0000025F939C7B80>
          └ <aiohttp.web_runner.AppRunner object at 0x0000025F951C83B0>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\web_runner.py", line 275, in setup
    self._server = await self._make_server()
    │    │               │    └ <function AppRunner._make_server at 0x0000025F939CC430>
    │    │               └ <aiohttp.web_runner.AppRunner object at 0x0000025F951C83B0>
    │    └ <member '_server' of 'BaseRunner' objects>
    └ <aiohttp.web_runner.AppRunner object at 0x0000025F951C83B0>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\web_runner.py", line 375, in _make_server
    await self._app.startup()
          │    └ <member '_app' of 'AppRunner' objects>
          └ <aiohttp.web_runner.AppRunner object at 0x0000025F951C83B0>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\web_app.py", line 416, in startup
    await self.on_startup.send(self)
          │    │               └ <Application 0x25f90f831f0>
          │    └ <property object at 0x0000025F939B7D10>
          └ <Application 0x25f90f831f0>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\signals.py", line 34, in send
    await receiver(*args, **kwargs)  # type: ignore
          │         │       └ {}
          │         └ (<Application 0x25f90f831f0>,)
          └ functools.partial(<function Executor._prepare_webhook.<locals>._wrap_callback at 0x0000025F951735E0>, <function on_startup at...

> File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\executor.py", line 260, in _wrap_callback
    return await cb(self.dispatcher)
                 │  │    └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000025F94F7B100>
                 │  └ <aiogram.utils.executor.Executor object at 0x0000025F91051FD0>
                 └ <function on_startup at 0x0000025F9516DF70>

  File "D:\Документы\Projects\school-timetable-bot\bot.py", line 27, in on_startup
    await bot.set_webhook(url=WEBHOOK_URL)
          │   │               └ '127.0.0.1/2041745221:AAE_8yJ8SpeNMWNPFBf8a5ff8gXXt9J5UmQ'
          │   └ <function Bot.set_webhook at 0x0000025F93B26430>
          └ <aiogram.bot.bot.Bot object at 0x0000025F94F7B0D0>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\bot.py", line 164, in set_webhook
    return await self.request(api.Methods.SET_WEBHOOK, payload, files)
                 │    │       │   │       │            │        └ {}
                 │    │       │   │       │            └ {'url': '127.0.0.1/2041745221:AAE_8yJ8SpeNMWNPFBf8a5ff8gXXt9J5UmQ'}
                 │    │       │   │       └ <aiogram.utils.helper.Item object at 0x0000025F92C69670>
                 │    │       │   └ <class 'aiogram.bot.api.Methods'>
                 │    │       └ <module 'aiogram.bot.api' from 'C:\\Users\\creeper\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\...
                 │    └ <function BaseBot.request at 0x0000025F93B1A280>
                 └ <aiogram.bot.bot.Bot object at 0x0000025F94F7B0D0>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
                 │   │            │    │        │    │       │             │       │     └ {}
                 │   │            │    │        │    │       │             │       └ {'url': '127.0.0.1/2041745221:AAE_8yJ8SpeNMWNPFBf8a5ff8gXXt9J5UmQ'}
                 │   │            │    │        │    │       │             └ 'setWebhook'
                 │   │            │    │        │    │       └ <aiogram.bot.bot.Bot object at 0x0000025F94F7B0D0>
                 │   │            │    │        │    └ TelegramAPIServer(base='https://api.telegram.org/bot{token}/{method}', file='https://api.telegram.org/file/bot{token}/{path}')
                 │   │            │    │        └ <aiogram.bot.bot.Bot object at 0x0000025F94F7B0D0>
                 │   │            │    └ <property object at 0x0000025F93B19130>
                 │   │            └ <aiogram.bot.bot.Bot object at 0x0000025F94F7B0D0>
                 │   └ <function make_request at 0x0000025F93ACF310>
                 └ <module 'aiogram.bot.api' from 'C:\\Users\\creeper\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\aiogram\\...

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           │            │       │        │             │        │             │        └ <function ClientResponse.text at 0x0000025F935D2C10>
           │            │       │        │             │        │             └ <ClientResponse(https://api.telegram.org/bot2041745221:AAE_8yJ8SpeNMWNPFBf8a5ff8gXXt9J5UmQ/setWebhook) [400 Bad Request]>
           │            │       │        │             │        │               <CI...
           │            │       │        │             │        └ 400
           │            │       │        │             └ <ClientResponse(https://api.telegram.org/bot2041745221:AAE_8yJ8SpeNMWNPFBf8a5ff8gXXt9J5UmQ/setWebhook) [400 Bad Request]>
           │            │       │        │               <CI...
           │            │       │        └ <property object at 0x0000025F934048B0>
           │            │       └ <ClientResponse(https://api.telegram.org/bot2041745221:AAE_8yJ8SpeNMWNPFBf8a5ff8gXXt9J5UmQ/setWebhook) [400 Bad Request]>
           │            │         <CI...
           │            └ 'setWebhook'
           └ <function check_result at 0x0000025F93AB7790>

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
    │          │          │      └ 'Bad Request: bad webhook: IP address 127.0.0.1 is reserved'
    │          │          └ <classmethod object at 0x0000025F93AC6910>
    │          └ <class 'aiogram.utils.exceptions.BadRequest'>
    └ <module 'aiogram.utils.exceptions' from 'C:\\Users\\creeper\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\...

  File "C:\Users\creeper\AppData\Local\Programs\Python\Python39\lib\site-packages\aiogram\utils\exceptions.py", line 141, in detect
    raise cls(description)
          │   └ 'bad request: bad webhook: ip address 127.0.0.1 is reserved'
          └ <class 'aiogram.utils.exceptions.BadRequest'>

aiogram.utils.exceptions.BadRequest: Bad webhook: ip address 127.0.0.1 is reserved
[28 Oct 2021 | 14:07:15] WARNING in bot.py function on_shutdown line 44 :: Shutting down bot...
[28 Oct 2021 | 14:51:19] SUCCESS in loader.py function <module> line 38 :: Подключение к Redis
[28 Oct 2021 | 14:51:19] SUCCESS in loader.py function <module> line 60 :: Подключение к PostgreSQL
[28 Oct 2021 | 14:51:19] WARNING in bot.py function on_startup line 35 :: Starting bot...
[28 Oct 2021 | 14:51:53] WARNING in bot.py function on_shutdown line 43 :: Shutting down bot...
